### ISSUE TITLE
Consider viewing data cumulatively, instead of just which filings are issued week to week

### ISSUE THREAD

**Issue by sraby** [housing-data-coalition/rtc-eviction-viz#12]

**Comment by sraby** [comment]
@lblok made this awesome [DataWrapper Prototype](https://www.datawrapper.de/_/xYWkY/). And Malika is now asking other RTC organizers what they think. Standing by for next steps!

**Comment by lblok** [comment]
Cumulative chart in [https://github.com/housing-data-coalition/rtc-eviction-viz/tree/activecases](activecases)
