### ISSUE TITLE
Line charts include an empty day/week/month for January 2019 after auto-updating data

### ISSUE THREAD

**Issue by sraby** [housing-data-coalition/rtc-eviction-viz#27]
I noticed a very bizarre issue pop up on our live site, which as far as I know I am unable to reproduce in development. In  83e8bc70193a674db1dc79141654342ce2bd9bf1, I fixed an issue where viewing our data by week would start our line charts with a week in between December 2019 and January 2020, which then looked totally fixed in production as well after deploying. I started to notice, however, that after every new day, the problem would resurface on production, showing an empty day, week, or month from January 2019 at the start of each line chart: 

<img width="1021" alt="Screen Shot 2020-12-21 at 9 31 55 AM" label="blah" src="https://user-images.githubusercontent.com/12834575/102788703-0f2e7380-4371-11eb-91cd-61960be9d382.png">

Our charts would NOT look like this in development, only production. Oddly enough, though, when I reran `yarn build-data` and `yarn deploy` in development, that seemed to fix the bug in production, even though there would be no noticeable change on dev: 

<img width="1039" alt="Screen Shot 2020-12-21 at 9 32 52 AM" src="https://user-images.githubusercontent.com/12834575/102788961-70eedd80-4371-11eb-8dbb-f293d4da785d.png">

I suspect this has something to do with our auto-running of our SQL code every morning, since the problem seems to resurface every new day. However, I can't figure out why this would be happening, and why we'd see a lack of parity between dev and prod like this.

**Comment by toolness** [comment]
Ooo, I'm not sure what's happening but I have a hunch this has something to do with time zones, since all our dev machines are likely set to EST but the GH Actions machine that runs our deploys is likely set to UTC.  It might be useful to try setting the timezone (perhaps using the [setup-timezone GH action](https://github.com/marketplace/actions/setup-timezone)) and see if that fixes anything.

**Comment by sraby** [comment]
Thank you Atul! I just added time zone setting to that GH action (#28) and it seemed to fix the issue [in production](https://housing-data-coalition.github.io/rtc-eviction-viz/index.html)! I'm going to wait to see if this doesn't revert back overnight, but it's looking like this is fixed!

**Comment by sraby** [comment]
Now a day later, this looks fixed! Yahoo!
