### ISSUE TITLE
Add interactive version of a filings map below the charts

### ISSUE THREAD

**Issue by sraby** [housing-data-coalition/rtc-eviction-viz#5]
@lblok made this awesome map prototype on DataWrapper that shows filings by zipcode (normalized by unit): https://www.datawrapper.de/_/Pv095/

Let's find a way to recreate this map using Vega Lite and display it below our chart.

**Comment by lblok** [comment]
@toolness I added a CSV of the data I used to make the datawrapper map but I need to update the SQL to output something like that, I manipulated it a lot in Excel.

**Comment by sraby** [comment]
This seems to be a duplicate of #14! Closing :)
